### ISSUE TITLE
Editing String fields takes no effect

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/meteor-api#61]
> However, I've found that while the 'add' API endpoint works fine, for some entities, the edit endpoint is returning a 200 status but not updating the record. This is very odd as I've tried the same operation on the legacy site and it works fine.

> E.g. For an Organization the following JSON code sent to the edit api endpoint works.

![image](https://github.com/opted-eu/meteor-api/assets/20080275/a450fb7b-510f-4d27-aac2-736f462fa4ec)

> However, this JSON for a LearningMaterial doesn't update the record even it gives a 200 response.

![image](https://github.com/opted-eu/meteor-api/assets/20080275/84019f44-4968-4ec9-b540-3f6feeae6aae)

**Comment by mrwunderbar666** [comment]
@iwellaway I think this issue should be fixed now.

**Comment by mrwunderbar666** [comment]
> Thanks for looking into these issues. The 'edit' endpoint is now updating select boxes which is great!
> I've also amended my code to use 'null' for updating text fields and can confrm that it works for the 'description' field.
> However, it's still not working for some other text fields:
> E.g. PoliticalParty.parlgov_id
![image](https://github.com/opted-eu/meteor-api/assets/20080275/42707ff2-d7f1-40c9-bc0c-43d2eb4cfbf2)

> This is not removing the text field 'parlgov_id' and seems to have no effect on it. It's the same for other text fields (E.g. name_abbrev & color_hex).


The default setting of `String` class prevents such fields from being overwritten / deleted

👉 Change default behaviour of `String` class and change `model.py` accordingly (only certain String fields should not be deletable)

**Comment by iwellaway** [comment]
Tested working using PoliticalParty.parlgov_id
