### ISSUE TITLE
Better handling of facets when editing / adding new entries

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/meteor-api#62]
Parsing facets is currently very poor. Improve handling of facets to support more complex requests:

@iwellaway 

![image](https://github.com/opted-eu/meteor-api/assets/20080275/221b5e7c-c850-410c-9e38-ba6bc524f48c)

> It stores it as the following:
 
![image](https://github.com/opted-eu/meteor-api/assets/20080275/b40b17af-a609-4a3d-babd-2e6017d8d627)

**Comment by iwellaway** [comment]
This is working for adding multiple documentation|kind now

**Comment by iwellaway** [comment]
This is working for adding multiple documentation|kind now

**Comment by mrwunderbar666** [comment]
Deleting list facet entries still not working
