### ISSUE TITLE
Mistakes in Data Model (required vs NA values)

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/meteor-api#63]
@iwellaway 
>  I've found several fields that, if not set when initially adding a new record, they get set to 'NA'. However, this fails to validate when editing if 'NA' is not one of their options (this usually happens for 'enum' fields with a hardcoded set of values. These are the fields that I have noticed this behvaiour occurring on:

> Tool.platforms
> ScientificPublication.paper_kind
> NewsSource.topical_focus

👉 platforms should be required, set default value to all three platforms
👉 paper_kind should be required
👉 topical_focus should not be required and have a NA value

**Comment by iwellaway** [comment]
Check as working with Tool.platforms and NewsSource.topical_focus
